### ISSUE TITLE
Libra 红名单 WebAPI v2 文档 | 小萧的个人博客

### ISSUE THREAD

**Issue by Steve-xmh** [Steve-xmh/blog#12]
https://steve-xmh.github.io/blog/2020/03/21/librewebapiv2doc/ 

 众所周知，因为一些内部开发人员对于使用 Python 有争议，最后协商选择使用 NodeJS 重新编写，同时和维护团队与阿尔法营的守护者老师深度讨论之后重新制定了第二个 WebAPI 版本。 该文档的内容以通过审核，现已可用。  注：旧版本的 API 仍然会保留，但是不建议继续使用，请尽快将请求链接转移至 v2！旧版 v1 API 链接  API 文档所有链接均使用 https://redlist

**Comment by kuailekai-1727** [comment]
emm...
![971C4B57-20FB-4423-83D3-F33907F1D322.jpeg](https://i.loli.net/2020/04/28/3c5PQntXKg6YvfV.jpg)

你知道我是谁吗？

**Comment by kuailekai-1727** [comment]
你的服务器哪里买的？

**Comment by Steve-xmh** [comment]
> @kuailekai-1727
> 你的服务器哪里买的？

不好意思，无可奉告

**Comment by kuailekai-1727** [comment]
友链申请：https://kuailekai.wordpress.com/

**Comment by Steve-xmh** [comment]
> @kuailekai-1727
> 友链申请：https://kuailekai.wordpress.com/

还是写一点东西吧，空荡荡的都不像博客

**Comment by wklcoca** [comment]
JavaScript 扩展 有离线版自己导入的吗？qwq我找不到(新人求助)
