### ISSUE TITLE
如何保护你的 Roblox 游戏公平/安全 | 小萧的个人博客

### ISSUE THREAD

**Issue by Steve-xmh** [Steve-xmh/blog#15]
https://steve-xmh.github.io/blog/2020/08/12/%E5%A6%82%E4%BD%95%E4%BF%9D%E6%8A%A4%E4%BD%A0%E7%9A%84-Roblox-%E6%B8%B8%E6%88%8F%E5%85%AC%E5%B9%B3-%E5%AE%89%E5%85%A8/#more 

 注：文章仓促完成，如果有误请不吝指正。  众所周知，游戏都有可能存在漏洞，而作弊者常常出现，他们破坏游戏规则，干扰玩家体验，甚至窃取游戏代码。至此在游戏有一定社区规模后，我们就不得不考虑游戏安全和公平问题了。借由亲身体验过游戏执行器（Executor）（即可以从外部向 Roblox Player 内执行完整的核心脚本（Core Script）的等级 Lua 代码的工具）的人。我向大家介绍 Rob

**Comment by yukitai** [comment]
hi
